#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# Wait Nomad
until nomad acl policy list > /dev/null; do
  sleep 1; done;

NOMAD_TOKEN="$(nomad acl bootstrap | tail -n +2 | head -n 1 | awk '{print $4}')"
export NOMAD_TOKEN=$NOMAD_TOKEN

# Write NOMAD_TOKEN as a local file
echo "$NOMAD_TOKEN" >> "/etc/nomad.d/token"

# .bashrc: Add a step to read the token from the local file
cat <<< 'export NOMAD_TOKEN=$(sudo cat /etc/nomad.d/token)' >> "$HOME/.bashrc"

# Print the token to stdout
echo "Nomad ACL Secret ID = $NOMAD_TOKEN"

# Set a nasty cron for the bug https://github.com/hashicorp/nomad/issues/10927
GIT_REPO=$(dirname "$0")
cp "${GIT_REPO}/systemd/csi-nasty-hack.service" /etc/systemd/system/
cp "${GIT_REPO}/systemd/csi-nasty-hack.timer"   /etc/systemd/system/
cp "${GIT_REPO}/systemd/csi-nasty-hack"         /etc/nomad.d/

# Start the service and the timer
systemctl daemon-reload
systemctl enable --now csi-nasty-hack.timer
