#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# Enable verbose mode
set -x

GIT_REPO=$(dirname "$0")

# Configure Nomad
mkdir -p /opt/nomad /etc/nomad.d
cp "${GIT_REPO}/nomad/production.hcl" /etc/nomad.d/default.hcl

# Configure systemd
cp "${GIT_REPO}/systemd/nomad.service" /etc/systemd/system/nomad.service

# Start Nomad
#
# Reference:
#   - https://github.com/hashicorp/terraform-aws-nomad/blob/master/modules/run-nomad/run-nomad
systemctl daemon-reload
systemctl enable --now nomad.service
