#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# Enable verbose mode
set -x

GIT_REPO=$(dirname "$0")

# Configure Consul
# Reference: https://learn.hashicorp.com/tutorials/consul/deployment-guide
mkdir -p /etc/consul.d /opt/consul
chown -R consul:consul /etc/consul.d /opt/consul
cp "${GIT_REPO}/consul/default.hcl" /etc/consul.d/
sudo -u consul consul validate /etc/consul.d/default.hcl

# Configure Nomad
# Reference: https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul
mkdir -p /opt/nomad /etc/nomad.d
cp "${GIT_REPO}/nomad/production.hcl" /etc/nomad.d/default.hcl

# Configure systemd
cp "${GIT_REPO}/systemd/consul.service" /etc/systemd/system/
cp "${GIT_REPO}/systemd/nomad.service" /etc/systemd/system/

# Start Consul and Nomad
#
# Reference:
#   - https://github.com/hashicorp/terraform-aws-consul/blob/master/modules/run-consul/run-consul
#   - https://github.com/hashicorp/terraform-aws-nomad/blob/master/modules/run-nomad/run-nomad
systemctl daemon-reload
systemctl enable consul.service nomad.service
systemctl restart consul.service nomad.service
