#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# This script would detach CSI volume claim whenever it is not claimed by any Nomad allocations.
# Bug: https://github.com/hashicorp/nomad/issues/10927

# Read and export the Nomad token
# Declare and assign separately to avoid masking return values. shellcheck(SC2155)
NOMAD_TOKEN=$(sudo cat /etc/nomad.d/token)
export NOMAD_TOKEN

detach_volume()
{
  # Fetch whether there is a running allocation.
  ALLOCS="$(nomad job allocs -t "{{range .}}{{print 1}}{{end}}" "$1")"
  if [ -z "$ALLOCS" ]; then
    echo "There is a allocation for $1."
  fi

  # Fetch whether there is a volume claim for the job.
  CLAIMED="$(nomad volume status -t "{{range .}}{{if eq .ID \"$A\"}}{{print 1}}{{end}}{{end}}")"
  if [ -z "$CLAIMED" ]; then
    echo "There is a volume for $1."
  fi

  # If there a volume claim for the job but no allocations for the job, detach it.
  if [[ -z "$ALLOCS" && -n "$CLAIMED" ]]; then
    echo "Trying to detach the volume..."
    NODE=$(nomad node status -t '{{range .}}{{print .ID}}{{end}}')
    nomad volume detach "$1" "$NODE"
  else
    echo 'No problem detected.'
  fi
}

detach_volume mysql
detach_volume caddycerts
