#!/bin/bash
set -euo pipefail; IFS=$'\n\t'

# This script would detach CSI volume claim whenever it is not claimed by any Nomad allocations.
# Bug: https://github.com/hashicorp/nomad/issues/10927

# Read and export the Nomad token
# Declare and assign separately to avoid masking return values. shellcheck(SC2155)
NOMAD_TOKEN=$(sudo cat /etc/nomad.d/token)
export NOMAD_TOKEN

detach_volume()
{
  # Fetch the names of the running allocations.
  # Use awk as `nomad job status` has no options for Go templating.
  ALLOCS="$(nomad job status --all-allocs "$1" | awk '/Allocations/,0' | tail -n +3 | awk '{if($6=="running")print $1}')"

  # Fetch whether there is a volume claim for the job.
  CLAIMED="$(nomad volume status -t "{{range .}}{{if eq .ID \"$1\"}}{{print 1}}{{end}}{{end}}")"

  # If there a volume claim for the job but no allocations for the job, detach it.
  if [[ -z "$ALLOCS" && -n "$CLAIMED" ]]; then
    NODE=$(nomad node status -t '{{range .}}{{print .ID}}{{end}}')
    nomad volume detach "$1" "$NODE"
  fi
}

detach_volume mysql
detach_volume caddycerts
